// SPDX-License-Identifier: MIT
// Copyright (C) 2025 Mutasem Kharma

package reporter

import (
	"fmt"
	"os"
	"strings"
	"time"

	"github.com/Mutasem-mk4/bola/internal/graph"
)

// WriteMarkdown generates a HackerOne/Bugcrowd-ready Markdown report.
func WriteMarkdown(findings []*graph.Finding, path, baseURL string) error {
	var sb strings.Builder

	// Header
	sb.WriteString("# BOLA/IDOR Vulnerability Report\n\n")
	sb.WriteString(fmt.Sprintf("**Generated by:** [bola](https://github.com/Mutasem-mk4/bola)  \n"))
	sb.WriteString(fmt.Sprintf("**Date:** %s  \n", time.Now().UTC().Format("2006-01-02 15:04:05 UTC")))
	sb.WriteString(fmt.Sprintf("**Target:** %s  \n\n", baseURL))

	// Summary
	high, medium, low := countByConfidence(findings)
	sb.WriteString("## Summary\n\n")
	sb.WriteString("| Severity | Count |\n")
	sb.WriteString("|----------|-------|\n")
	sb.WriteString(fmt.Sprintf("| 🔴 High | %d |\n", high))
	sb.WriteString(fmt.Sprintf("| 🟡 Medium | %d |\n", medium))
	sb.WriteString(fmt.Sprintf("| 🔵 Low | %d |\n", low))
	sb.WriteString(fmt.Sprintf("| **Total** | **%d** |\n\n", high+medium+low))

	sb.WriteString("---\n\n")

	// Individual findings
	findingNum := 0
	for _, f := range findings {
		if strings.HasPrefix(f.Notes, "[DEDUPLICATED]") {
			continue
		}

		findingNum++
		writeFinding(&sb, findingNum, f, baseURL)
	}

	if findingNum == 0 {
		sb.WriteString("No BOLA/IDOR vulnerabilities were detected.\n")
	}

	return os.WriteFile(path, []byte(sb.String()), 0644)
}

// writeFinding writes a single finding in HackerOne-ready format.
func writeFinding(sb *strings.Builder, num int, f *graph.Finding, baseURL string) {
	method := ""
	path := ""
	if f.Endpoint != nil {
		method = f.Endpoint.Method
		path = f.Endpoint.Path
	}

	severity := "Low"
	switch f.ConfidenceLevel {
	case graph.ConfidenceHigh:
		severity = "High"
	case graph.ConfidenceMedium:
		severity = "Medium"
	}

	sb.WriteString(fmt.Sprintf("## Finding #%d: BOLA in %s %s\n\n", num, method, path))

	sb.WriteString(fmt.Sprintf("**Severity:** %s  \n", severity))
	sb.WriteString(fmt.Sprintf("**Confidence:** %s  \n", f.ConfidenceLevel))
	sb.WriteString(fmt.Sprintf("**Endpoint:** `%s %s`  \n", method, path))
	sb.WriteString(fmt.Sprintf("**Owner Identity:** %s  \n", f.OwnerIdentity))
	sb.WriteString(fmt.Sprintf("**Tester Identity:** %s  \n\n", f.TesterIdentity))

	// Description
	sb.WriteString("### Description\n\n")
	sb.WriteString(fmt.Sprintf("The endpoint `%s %s` is vulnerable to Broken Object Level Authorization (BOLA/IDOR). ", method, path))
	sb.WriteString(fmt.Sprintf("A user with the identity **%s** was able to access resources owned by **%s** ", f.TesterIdentity, f.OwnerIdentity))
	sb.WriteString("by replaying the same request with different authentication credentials.\n\n")

	sb.WriteString(fmt.Sprintf("- **Owner's response status:** %d\n", f.OwnerStatus))
	sb.WriteString(fmt.Sprintf("- **Tester's response status:** %d\n", f.TesterStatus))
	sb.WriteString(fmt.Sprintf("- **Response similarity:** %.1f%%\n", f.Similarity*100))
	sb.WriteString(fmt.Sprintf("- **Response size delta:** %.1f%%\n\n", f.SizeDelta*100))

	// Steps to reproduce
	sb.WriteString("### Steps to Reproduce\n\n")
	sb.WriteString(fmt.Sprintf("1. Authenticate as **%s** (resource owner)\n", f.OwnerIdentity))
	sb.WriteString(fmt.Sprintf("2. Access the endpoint `%s %s`\n", method, path))
	sb.WriteString(fmt.Sprintf("3. Note the response (status %d, data returned)\n", f.OwnerStatus))
	sb.WriteString(fmt.Sprintf("4. Authenticate as **%s** (attacker)\n", f.TesterIdentity))
	sb.WriteString("5. Replay the same request with the attacker's credentials (see curl below)\n")
	sb.WriteString(fmt.Sprintf("6. Observe: the server returns status %d with %.1f%% similar data\n\n",
		f.TesterStatus, f.Similarity*100))

	// Impact
	sb.WriteString("### Impact\n\n")
	sb.WriteString("An attacker can access, modify, or delete resources belonging to other users ")
	sb.WriteString("by manipulating object identifiers in this endpoint. This can lead to:\n\n")
	sb.WriteString("- **Unauthorized data access** — reading other users' private data\n")
	sb.WriteString("- **Data tampering** — modifying resources owned by other users\n")
	sb.WriteString("- **Privacy violation** — exposure of personally identifiable information (PII)\n\n")

	// Reproduction
	sb.WriteString("### Reproduction\n\n")
	sb.WriteString("```bash\n")
	sb.WriteString(f.CurlCommand)
	sb.WriteString("\n```\n\n")

	// Analysis notes
	if f.Notes != "" {
		sb.WriteString("### Analysis Notes\n\n")
		sb.WriteString(f.Notes)
		sb.WriteString("\n\n")
	}

	sb.WriteString("---\n\n")
}
