// SPDX-License-Identifier: MIT
// Copyright (C) 2025 Mutasem Kharma

package reporter

import (
	"fmt"
	"os"
	"strings"
	"time"

	"github.com/Mutasem-mk4/bola/internal/graph"
)

// ExportMarkdown generates a HackerOne/Bugcrowd-ready Markdown report.
func ExportMarkdown(findings []*graph.Finding, path, baseURL string) error {
	var sb strings.Builder

	sb.WriteString("# BOLA/IDOR Vulnerability Report\n\n")
	sb.WriteString(fmt.Sprintf("**Generated by:** [bola](https://github.com/Mutasem-mk4/bola)  \n"))
	sb.WriteString(fmt.Sprintf("**Date:** %s  \n", time.Now().UTC().Format("2006-01-02 15:04:05 UTC")))
	sb.WriteString(fmt.Sprintf("**Target:** %s  \n\n", baseURL))

	high, medium, low := countByConfidence(findings)
	sb.WriteString("## Summary\n\n")
	sb.WriteString("| Severity | Count |\n|----------|-------|\n")
	sb.WriteString(fmt.Sprintf("| 🔴 High | %d |\n", high))
	sb.WriteString(fmt.Sprintf("| 🟡 Medium | %d |\n", medium))
	sb.WriteString(fmt.Sprintf("| 🔵 Low | %d |\n", low))
	sb.WriteString(fmt.Sprintf("| **Total** | **%d** |\n\n---\n\n", high+medium+low))

	num := 0
	for _, f := range findings {
		if strings.HasPrefix(f.Notes, "[DEDUPLICATED]") {
			continue
		}
		num++

		method, fpath := "", ""
		if f.Endpoint != nil {
			method = f.Endpoint.Method
			fpath = f.Endpoint.Path
		}

		severity := "Low"
		switch f.ConfidenceLevel {
		case graph.ConfidenceHigh:
			severity = "High"
		case graph.ConfidenceMedium:
			severity = "Medium"
		}

		sb.WriteString(fmt.Sprintf("## Finding #%d: BOLA in %s %s\n\n", num, method, fpath))
		sb.WriteString(fmt.Sprintf("**Severity:** %s  \n", severity))
		sb.WriteString(fmt.Sprintf("**Confidence:** %s  \n", f.ConfidenceLevel))
		sb.WriteString(fmt.Sprintf("**Endpoint:** `%s %s`  \n", method, fpath))
		sb.WriteString(fmt.Sprintf("**Owner Identity:** %s  \n", f.OwnerIdentity))
		sb.WriteString(fmt.Sprintf("**Tester Identity:** %s  \n\n", f.TesterIdentity))

		sb.WriteString("### Description\n\n")
		sb.WriteString(fmt.Sprintf("The endpoint `%s %s` is vulnerable to Broken Object Level Authorization (BOLA/IDOR). ", method, fpath))
		sb.WriteString(fmt.Sprintf("A user with the identity **%s** was able to access resources owned by **%s** ", f.TesterIdentity, f.OwnerIdentity))
		sb.WriteString("by replaying the same request with different authentication credentials.\n\n")
		sb.WriteString(fmt.Sprintf("- **Owner status:** %d  |  **Tester status:** %d\n", f.OwnerStatus, f.TesterStatus))
		sb.WriteString(fmt.Sprintf("- **Response similarity:** %.1f%%\n", f.Similarity*100))
		sb.WriteString(fmt.Sprintf("- **Response size delta:** %.1f%%\n\n", f.SizeDelta*100))

		sb.WriteString("### Steps to Reproduce\n\n")
		sb.WriteString(fmt.Sprintf("1. Authenticate as **%s** (resource owner)\n", f.OwnerIdentity))
		sb.WriteString(fmt.Sprintf("2. Access `%s %s` — note the response\n", method, fpath))
		sb.WriteString(fmt.Sprintf("3. Authenticate as **%s** (attacker)\n", f.TesterIdentity))
		sb.WriteString("4. Replay the same request with attacker credentials:\n\n")
		sb.WriteString("```bash\n")
		sb.WriteString(f.CurlCommand)
		sb.WriteString("\n```\n\n")
		sb.WriteString(fmt.Sprintf("5. Observe: the server returns status %d with %.1f%% similar data\n\n", f.TesterStatus, f.Similarity*100))

		sb.WriteString("### Impact\n\n")
		sb.WriteString("An attacker can access resources belonging to other users by manipulating object identifiers. This can lead to:\n")
		sb.WriteString("- **Unauthorized data access** — reading other users' private data\n")
		sb.WriteString("- **Data tampering** — modifying resources owned by other users\n")
		sb.WriteString("- **Privacy violation** — exposure of PII\n\n")

		if f.Notes != "" {
			sb.WriteString("### Analysis Notes\n\n")
			sb.WriteString(f.Notes + "\n\n")
		}

		sb.WriteString("---\n\n")
	}

	if num == 0 {
		sb.WriteString("No BOLA/IDOR vulnerabilities were detected.\n")
	}

	return os.WriteFile(path, []byte(sb.String()), 0644)
}
